language: node_js

node_js:
  - "12.16.1"

script:
  - echo "Deploy"
  - echo $FIREBASE_TOKEN

install:
  - npm install -g firebase-tools

# after_success:
#   - firebase deploy --token $FIREBASE_TOKEN

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: ryosuke-ku