language: node_js

node_js:
  - "12.16.1"

script:
  - echo "Deploy"
#   - echo $FIREBASE_TOKEN

install:
  - npm install -g firebase-tools

deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN_1
  project: $FIREBASE_PROJECT
